### ISSUE TITLE
Change the date and correct typos

### ISSUE THREAD

**Issue by JasmineCrozier** [Praqma/web-codeall#28]
The next gathering is on 13-14th November, not 12-13th.
I'd like us to stick to English, so use Gothenburg, not Göteborg.

Typos:
**You**’ve gotta be ambitious about Continues Delivery**,** DevTestOps**,** and Automation
You’ve gotta have an invitation.

If you need an invite - mail us as alliance@praqma.com and explain **your** case.

**Comment by JasmineCrozier** [comment]
@lakruzz Can I correct these now, or do i need to get the codeall repo on my laptop, like for praqma and code-conf?

**Comment by lakruzz** [comment]
@JasmineCrozier 


You can fix stuff in this repo :-) 
- only thing you need to know, is that at this point, we haven't setup a pipeline yet - so you will have to  use the `--local` switch to your `deliver`

## Get the repo

```shell
cd ~/github/praqma
git clone git@github.com:Praqma/web-codeall.git
cd web-codeall
atom .
```
Hack away - using the phlow just like you are used to

```shell
git workon 30
...
...
git wrapup
git deliver --local
````
