### ISSUE TITLE
Redirect from Praqma.com

### ISSUE THREAD

**Issue by lakruzz** [Praqma/web-codeall#31]
- [ ] redirect www.praqma.com/codeall 
- [ ] redirect www.praqma.com/alliance
- [ ] www.Josra.org
- [ ] mention at www.praqma.com/services

**Comment by praqma-thi** [comment]
Giving this a little bump.

Looks like we'll need a little write-up of the code alliance under praqma.com/services. (@JasmineCrozier ?)

After which we can redirect some old links to http://alliance.praqma.com/.
(@anetacamo  ?)

**Comment by JasmineCrozier** [comment]
@praqma-thi The alliance is mentioned under Community instead (it's not a service)
https://www.praqma.com/community/codeall/

**Comment by JasmineCrozier** [comment]
But yes for all the redirect

**Comment by JasmineCrozier** [comment]
We'll redirect to praqma.com and code-conf for the 9th gathering
