### ISSUE TITLE
Mail group alliance@praqma.com

### ISSUE THREAD

**Issue by lakruzz** [Praqma/web-codeall#32]
Currently it's a catch-all. It should be a real mail group

**Comment by buep** [comment]
We also have codeall@praqma.net consisting of Adam, Bue, Lars, Mike, Mona (suspended user).
I added Jasmine.

I also created alliance@praqma.com with the same people. The group is created a `team (internet)` meaning it is invitation only (the alias) but all of Praqma can read things there, and the hole internet can send mail to it.

Added information to code-alliance README.

**Comment by buep** [comment]
And though our google suite mention the alias on .net, it also works for .com

**Comment by buep** [comment]
Also updated our readme in the code alliance repo with a bit of information https://github.com/Praqma/code-alliance/commit/ab3a81e5db2ae7636299a2ddd33c9a731bb55c13
