### ISSUE TITLE
I would like blogs about alliance from praqma.com shown in alliance subsite

### ISSUE THREAD

**Issue by buep** [Praqma/web-codeall#51]
Without any copy paste.

**Comment by buep** [comment]
Any good inputs on how this could be done?

**Comment by kryptag** [comment]
the only way i can think of, is to use a url that filters for alliance blog posts and then create a iframe that references that url. what happens is that you open the website inside the iframe and that way have it "embedded" into the website. this might become heavy in terms of load, so it might not be optimal for phones or slow connections. other than that we might wanna look into some "shared" resources that we can fetch from both sites.

**Comment by buep** [comment]
Great, thanks for the inputs.

Shared resources somehow it is then.
