### ISSUE TITLE
Charter needs an update

### ISSUE THREAD

**Issue by JasmineCrozier** [Praqma/web-codeall#65]
I have updated the website with the 8th gathering sign up: https://github.com/Praqma/web-codeall/issues/64

However, the part of the Charter about Gatherings needs an update. It states that Praqma is covering all costs and that gathering are hosted at companies. It needs an update.

http://alliance.praqma.com/charter/

"At least once every half year, Praqma is responsible for organizing a gathering, that shall be open to all members.

The gatherings may be **hosted at facilities and venues at the members’ organizations.** **Expenses for executing the gatherings shall be covered by Praqma.**

Each alliance member is entitled to register two self-appointed (chief and geek) organization representatives to participate, **free of additional cost**, at the gatherings.

Each alliance member is entitled to send more participants to the gatherings than just the two designated roles. However, **additional gathering participants may be charged a meet-up fee to cover the venue and catering costs of the gathering.**"

**Comment by JasmineCrozier** [comment]
@buep I talked with @lakruzz on Friday and we agree that we need a new version of this Charter before communicating too much about the new format. It would look very inconsistent, if anyone read that you pay 5000 kr in one place and that it's all free in another place.

Lars suggested that you give this new Charter a try, and also update the section on Members.

**Comment by buep** [comment]
Members page, see #67 for updates.

**Comment by buep** [comment]
@lakruzz made a small rewrite to make it fit the new code camp format... if the text isn't easy to grasp or understand, a think a slightly bigger change is needed.
... just tried edit to new format, with out to many changes.
