### ISSUE TITLE
Gathering page needs a new layout

### ISSUE THREAD

**Issue by JasmineCrozier** [Praqma/web-codeall#66]
If this page is supposed to show all gatherings, we need a different layout.
http://alliance.praqma.com/gatherings/

Right now I kept the info and program of the 7th gathering below the 8th gathering info, because I am not sure what the plan is for this microsite.

**Comment by buep** [comment]
It should just show the up-coming gathering, or until then the past one if no new is planned.

I'll edit it.

**Comment by buep** [comment]
closed with this cahnge https://github.com/Praqma/web-codeall/commit/54f43124fc22dc4d459dd17f0104498cb98b78d2
