### ISSUE TITLE
Add usual start and end time schedules to gatherings page

### ISSUE THREAD

**Issue by buep** [Praqma/web-codeall#69]
> We will start on the 1st day at 11.00 (you are welcome from 10.00 though) and end on the 2nd day at 15.00, so you have to time travel.

**Comment by mortench3000** [comment]
@buep You may want to rephrase the last part of the sentence since 'time travel' has not yet been invented...
Maybe along the lines of
> ... so you can plan your travel

**Comment by buep** [comment]
Thanks @mortench3000 - fixed it.
