### ISSUE TITLE
Our pipeline fails on fonts not being found

### ISSUE THREAD

**Issue by buep** [Praqma/web-codeall#70]
https://jenkins.praqma.cloud/view/Website_Pipelines/view/alliance.praqma.com/job/Web_alliance.praqma.com-linkcheck/2/warningsResult/

The real problem is the ccs including fonts that can't be found

http://alliance.praqma.com/fonts/bootstrap/glyphicons-halflings-regular.woff2: (404 Not Found) -

```
josra.css:1, 2, Priority: High
http://alliance.praqma.com/fonts/bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular: (404 Not Found) -

josra.css:1, 2, Priority: High
http://alliance.praqma.com/fonts/bootstrap/glyphicons-halflings-regular.woff: (404 Not Found) -

josra.css:1, 2, Priority: High
http://alliance.praqma.com/fonts/bootstrap/glyphicons-halflings-regular.eot: (404 Not Found) -

josra.css:1, 2, Priority: High
http://alliance.praqma.com/fonts/bootstrap/glyphicons-halflings-regular.ttf: (404 Not Found) -
```

See Details tab here: https://jenkins.praqma.cloud/view/Website_Pipelines/view/alliance.praqma.com/job/Web_alliance.praqma.com-linkcheck/2/warningsResult/#

**Comment by buep** [comment]
@anetacamo do you have time to help with this?

Here is a lot of information from our slack thread - probably pretty easy to fix for you? https://praqma.slack.com/archives/C0GV33EH4/p1520429981000463

bue.petersen [1 hour ago]
@bicschneider why is this a compiler warning? https://jenkins.praqma.cloud/job/Web_alliance.praqma.com-linkcheck/2/warningsResult/package.45/source.7071580434517153979/#1


bue.petersen [1 hour ago]
@bicschneider this is also a false positive... the file is there: http:/alliance.praqma.com/css/josra.css


bue.petersen [1 hour ago]
I see it in my browser


bicschneider [27 minutes ago]
Concerning the `Console output`: I have no clue as there is an option explicit to include the this which is off ..


bue.petersen [26 minutes ago]
But can we get rid of that false positive?


bicschneider [26 minutes ago]
but the warning plugin is configured to not fail if only that is present


bicschneider [26 minutes ago]
this:
```http://alliance.praqma.com/fonts/bootstrap/glyphicons-halflings-regular.woff2: (404 Not Found) -

josra.css:1, 2, Priority: High
http://alliance.praqma.com/fonts/bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular: (404 Not Found) -

josra.css:1, 2, Priority: High
http://alliance.praqma.com/fonts/bootstrap/glyphicons-halflings-regular.woff: (404 Not Found) -

josra.css:1, 2, Priority: High
http://alliance.praqma.com/fonts/bootstrap/glyphicons-halflings-regular.eot: (404 Not Found) -

josra.css:1, 2, Priority: High
http://alliance.praqma.com/fonts/bootstrap/glyphicons-halflings-regular.ttf: (404 Not Found) -
```
?


bicschneider [25 minutes ago]
Go to `Details` (edited)

bue.petersen [25 minutes ago]
But I don't want an unstable job either if it is not true

bicschneider [24 minutes ago]
it is issues in the josra.css and not the josra.css itself

bue.petersen [23 minutes ago]
Yes I see it ... the output isn't very good. I'll fix them.

bicschneider [23 minutes ago]
I recall a discussion in the "old" days about fonts

bue.petersen [22 minutes ago]
https://jenkins.praqma.cloud/view/Website_Pipelines/view/alliance.praqma.com/But where are there only one job and it is red here?

bicschneider [22 minutes ago]
yes.. no ready branches yes and the PiP fails

bicschneider [22 minutes ago]
:disappointed:

bue.petersen [22 minutes ago]
ok

bicschneider [22 minutes ago]
so I have just triggered the "trigger" job to get the rest of pipeline

bicschneider [20 minutes ago]
the `old` discussion if PiP should pass as "green" if no branches available (Ex: check out integration branch)

bicschneider [19 minutes ago]
but no further comments needed for that :wink: (edited)

bue.petersen [18 minutes ago]
@florent can you have a look problem above and fix the problem with the fonts? Next time you work? https://github.com/Praqma/web-codeall/issues/70

bue.petersen [18 minutes ago]
I didn't see you triggered it manual

florent [17 minutes ago]
Fonts are loaded client side, thats why it fails

bicschneider [17 minutes ago]
The problem with the `warning` plugin is that it file based and not string based

bue.petersen [16 minutes ago]
so it is a false positive you say @florent?

bicschneider [16 minutes ago]
refresh

bicschneider [16 minutes ago]
@florent Why do we not see it on the other sites then?

bicschneider [15 minutes ago]
We could add a "ignore" to it

bicschneider [15 minutes ago]
let me check the other sites

florent [14 minutes ago]
wait, these errors seem a bit weird. Don't think these are because of what i said. this is files we are missing locally

bicschneider [14 minutes ago]
I cannot see from praqma.com that is ignored

florent [8 minutes ago]
the problem is in https://github.com/Praqma/web-codeall/blob/ebef67bf72c4bfc1f45efdb8c9c106eb45de658a/bower_components/bootstrap/package.js

florent [8 minutes ago]
line 17 - 21

bue.petersen [7 minutes ago]
and we're not using those fonts since the website works and they are not there? So I can delete the lines?

florent [5 minutes ago]
im not sure, because they are a part of Bootstrap. But i guess you could test it, and try to build it locally. There will be errors in the browser console if it is needed by other bootstrap components. Just to address my first comment, the pipeline works fine and this is actually an error. it's reported multiple places https://github.com/twbs/bootstrap-sass/issues/592

bicschneider [4 minutes ago]
What is the diff to praqma.com?

bue.petersen [4 minutes ago]
so if there are errors in the browser console how do one then add those files as resources?

florent [4 minutes ago]
maybe it's the bootstrap version

florent [3 minutes ago]
the best would be to try to read up on the bug reports and fixes people have commented on the different issues, and or update Bootstrap.

bue.petersen [< 1 minute ago]
All - right then... then it is for sure an Aneta or Florent issues... :wink: I'll see if Aneta have time to help

**Comment by buep** [comment]
@anetacamo any news on this one - when do you think you have time?

**Comment by anetacamo** [comment]
@buep Sorry Bue. Looking into it finally now :) Ill try to be faster next time!

**Comment by anetacamo** [comment]
@buep should not be a problem now with finding the fonts

**Comment by bicschneider** [comment]
@anetacamo 
It seems that the path are not correct: Example
`http://alliance.praqma.com/fonts/bootstrap/glyphicons-halflings-regular.woff2: (404 Not Found) `
.. but the real path on the webserver is:
`http://alliance.praqma.com/fonts/glyphicons-halflings-regular.woff2`
.. so maybe the solution is to move it to reference path?

**Comment by buep** [comment]
@anetacamo will you fix?
